SELECT VILLA_ID, VILLA_NAME
FROM VILLA
WHERE VILLA_ID IN (SELECT VILLA_ID FROM CATALOG1
                   WHERE FEATURE_ID=(SELECT FEATURE_ID FROM FEATURE WHERE FEATURE_NAME='Jacuzzi') 
                   MINUS
                   SELECT VILLA_ID FROM CATALOG1
                   WHERE FEATURE_ID = (SELECT FEATURE_ID FROM FEATURE WHERE FEATURE_NAME='pets allowed'));