SELECT USER_ID,USER_FNAME,USER_LNAME
FROM USER1
WHERE USER_ID IN
(SELECT DISTINCT R.USER_ID
FROM RESERVATION R,RESERVATION R1
WHERE ((TO_DATE(R.RESERVATION_SDATE,'dd-MM-RRRR') BETWEEN TO_DATE(R1.RESERVATION_SDATE,'dd-MM-RRRR') AND TO_DATE(R1.RESERVATION_EDATE,'dd-MM-RRRR')-1)
                     OR  (TO_DATE(R.RESERVATION_EDATE,'dd-MM-RRRR') BETWEEN TO_DATE(R1.RESERVATION_SDATE,'dd-MM-RRRR')+1 AND TO_DATE(R1.RESERVATION_EDATE,'dd-MM-RRRR')))
                     AND R.USER_ID=R1.USER_ID AND R.RESERVATION_ID != R1.RESERVATION_ID)
