SELECT USER_FNAME AS OWNER_FNAME,USER_LNAME AS OWNER_LNAME
FROM USER1
WHERE USER_ID IN
(SELECT PERCENTAGE_TABLE.OWNER_ID
FROM
(SELECT FIRST_YEAR.OWNER_ID,(SECOND_YEAR.RESERVE_DAYS/FIRST_YEAR.RESERVE_DAYS) * 100 PERCENT_INCREASE
FROM(SELECT V.OWNER_ID,SUM(R.RESERVATION_EDATE-R.RESERVATION_SDATE) AS RESERVE_DAYS
      FROM RESERVATION R JOIN VILLA V ON R.VILLA_ID=V.VILLA_ID
      WHERE R.RESERVATION_SDATE > TO_DATE('01-01-2013','dd-MM-RRRR') AND R.RESERVATION_EDATE < TO_DATE('31-08-2013','dd-MM-RRRR')
      GROUP BY V.OWNER_ID) FIRST_YEAR
      JOIN
      (SELECT V.OWNER_ID,SUM(R.RESERVATION_EDATE-R.RESERVATION_SDATE) AS RESERVE_DAYS
      FROM RESERVATION R JOIN VILLA V ON R.VILLA_ID=V.VILLA_ID
      WHERE R.RESERVATION_SDATE > TO_DATE('01-01-2014','dd-MM-RRRR') AND R.RESERVATION_EDATE < TO_DATE('31-08-2014','dd-MM-RRRR')
      GROUP BY V.OWNER_ID) SECOND_YEAR
      ON FIRST_YEAR.OWNER_ID=SECOND_YEAR.OWNER_ID) PERCENTAGE_TABLE
WHERE PERCENTAGE_TABLE.PERCENT_INCREASE >= 10);
