
SELECT AVG(EXTRACT( YEAR FROM TO_DATE(R.RESERVATION_SDATE,'dd-MM-RRRR')) - EXTRACT( YEAR FROM TO_DATE(U.USER_DOB,'dd-MM-RRRR'))) AVERAGE_AGE
FROM RESERVATION R JOIN USER1 U ON R.USER_ID=U.USER_ID
WHERE RESERVATION_SDATE >= TO_DATE('01-09-2013','dd-MM-RRRR') AND RESERVATION_SDATE <= TO_DATE('31-12-2013','dd-MM-RRRR');
