SELECT V.VILLA_ID,U.USER_ID OWNER_ID,U.USER_FNAME OWNER_FNAME,U.USER_LNAME OWNER_LNAME
FROM USER1 U,VILLA V
WHERE U.USER_ID=V.OWNER_ID
AND V.VILLA_ID IN(  SELECT TOP_VILLA.VILLA_ID
                    FROM (SELECT VILLA_ID,AVG(REVIEW_RATING) AVG_RATING 
                          FROM REVIEW
                          GROUP BY VILLA_ID
                          ORDER BY AVG_RATING DESC) TOP_VILLA
                    WHERE ROWNUM < 4);