SELECT VILLA_ID,VILLA_NAME
FROM(SELECT R.VILLA_ID,V.VILLA_NAME,SUM(R.RESERVATION_EDATE - R.RESERVATION_SDATE) RESERVE_DAYS 
      FROM RESERVATION R JOIN VILLA V ON R.VILLA_ID=V.VILLA_ID 
      WHERE R.RESERVATION_SDATE >= TO_DATE('01-01-2014','dd-MM-RRRR') AND R.RESERVATION_EDATE <= TO_DATE('31-12-2014','dd-MM-RRRR')
      GROUP BY R.VILLA_ID,V.VILLA_NAME
      ORDER BY RESERVE_DAYS DESC)
WHERE ROWNUM < 2;