SELECT OWNER_TOTAL_VILLAS.OWNER_ID,OWNER_NOT_RENTED_VILLAS.NO_NOT_RENTED/OWNER_TOTAL_VILLAS.TOTAL AS VACANCY_RATIO
FROM
(SELECT OWNER_ID,COUNT(VILLA_ID) AS TOTAL
FROM VILLA
GROUP BY OWNER_ID) OWNER_TOTAL_VILLAS
JOIN
(SELECT TOTAL_VILLAS.OWNER_ID,TOTAL_VILLAS.TOTAL_OWNED-VILLAS_RENTED.TOTAL_RENTED AS NO_NOT_RENTED
FROM
(SELECT OWNER_ID,COUNT(VILLA_ID) TOTAL_OWNED
FROM VILLA
GROUP BY OWNER_ID) TOTAL_VILLAS 
LEFT OUTER JOIN
(SELECT OWNER.OWNER_ID,NVL(RENTED.TOTAL_RENTED,0) TOTAL_RENTED
FROM OWNER LEFT OUTER JOIN
(SELECT V.OWNER_ID,COUNT(R.VILLA_ID) TOTAL_RENTED
FROM RESERVATION R,VILLA V
WHERE R.VILLA_ID=V.VILLA_ID
AND TO_DATE('08/15/2014','MM/dd/RRRR') BETWEEN TO_DATE(RESERVATION_SDATE,'dd-MM-RRRR') AND TO_DATE(RESERVATION_EDATE,'dd-MM-RRRR')
GROUP BY V.OWNER_ID) RENTED ON OWNER.OWNER_ID=RENTED.OWNER_ID) VILLAS_RENTED 
ON TOTAL_VILLAS.OWNER_ID=VILLAS_RENTED.OWNER_ID) OWNER_NOT_RENTED_VILLAS
ON OWNER_TOTAL_VILLAS.OWNER_ID=OWNER_NOT_RENTED_VILLAS.OWNER_ID
ORDER BY OWNER_TOTAL_VILLAS.OWNER_ID;